# Generated by Django 5.0.1 on 2024-02-05 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('head', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='media')),
                ('disc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256)),
                ('user_comment', models.TextField(blank=True)),
                ('user_data', models.DateTimeField(auto_now_add=True)),
                ('user_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.news')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='pages_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.pages'),
        ),
    ]
